export const ADD_SERVICE = 'ADD_SERVICE';
export const EDIT_SERVICE ='DELETE_SERVICE';
export const DELETE_SERVICE ='EDIT_SERVICE';
export const FILTER_SERVICES ='FILTER_SERVICES';
export const CHANGE_SERVICE_FIELD = 'CHANGE_SERVICE_FIELD';
export const CLEAR_SERVICE_FIELDS = 'CLEAR_SERVICE_FIELDS';
export const FILL_SERVICE_FIELDS = 'FILL_SERVICE_FIELDS';
export const CHANGE_SEARCH_FIELD = 'CHANGE_SEARCH_FIELD';


export default {
  ADD_SERVICE,
  EDIT_SERVICE,
  DELETE_SERVICE,
  FILTER_SERVICES,
  CHANGE_SERVICE_FIELD,
  CLEAR_SERVICE_FIELDS,
  FILL_SERVICE_FIELDS,
  CHANGE_SEARCH_FIELD,
};